storage:
  files:
    - path: /opt/beserver/minecraft.env
      filesystem: root
      overwrite: true
      mode: 0644
      contents:
        inline: |
          EULA=TRUE
          VERSION=LATEST
          SERVER_PORT=19132
          CORRECT_PLAYER_MOVEMENT=
          PLAYER_MOVEMENT_DURATION_THRESHOLD_IN_MS=500
          PLAYER_MOVEMENT_DISTANCE_THRESHOLD=0.3
          PLAYER_MOVEMENT_SCORE_THRESHOLD=20
          SERVER_AUTHORITATIVE_MOVEMENT=true
          TEXTUREPACK_REQUIRED=false
          DEFAULT_PLAYER_PERMISSION_LEVEL=member
          LEVEL_SEED=
          LEVEL_NAME=default
          MAX_THREADS=8
          PLAYER_IDLE_TIMEOUT=30
          TICK_DISTANCE=4
          VIEW_DISTANCE=32
          WHITE_LIST=false
          ONLINE_MODE=true
          MAX_PLAYERS=10
          ALLOW_CHEATS=false
          LEVEL_TYPE=default
          DIFFICULTY=normal
          GAMEMODE=survival
          SERVER_NAME=Minecraft Bedrock Server for Azure

    - path: /opt/bin/docker-compose
      filesystem: root
      overwrite: true
      mode: 0755
      contents:
        remote:
          url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64

    - path: /opt/beserver/docker-compose.yml
      filesystem: root
      overwrite: true
      mode: 0644
      contents:
        inline: |
          version: '3'

          services:
            beserver:
              container_name: beserver
              image: itzg/minecraft-bedrock-server
              ports:
                - "19132:19132/udp"
              volumes:
                - "nfs-volume:/data"
              stdin_open: true
              tty: true
              env_file:
                - minecraft.env
              restart: always

          volumes:
            nfs-volume:
              name: beserver-data
              driver_opts:
                type: nfs
                o: "addr=${STNAME}.privatelink.blob.core.windows.net.,rw,sec=sys,vers=3,nolock,proto=tcp"
                device: ":/${STNAME}/${SHARENAME}"

    - path: /opt/beserver/get-azure-env.sh
      filesystem: root
      overwrite: true
      mode: 0755
      contents:
        inline: |
          #!/bin/sh

          OUTPATH='/opt/beserver/.env'

          # get storage account name from VM meta data
          userdata=$(curl -s -H Metadata:true --noproxy \* 'http://169.254.169.254/metadata/instance?api-version=2021-02-01' \
            | jq '.compute.userData' -j \
            | base64 --decode)

          stname=$(echo ${userdata} | cut -d',' -f 1)
          sharename=$(echo ${userdata} | cut -d',' -f 2)

          cat <<EOF >${OUTPATH}
          STNAME=${stname}
          SHARENAME=${sharename}
          EOF

          exit 0

systemd:
  units:
    - name: docker.service
      enabled: true

    - name: beserver.service
      enabled: true
      contents: |
        [Unit]
        Description=Minecraft BE Server Service
        Requires=docker.service
        After=docker.service

        [Service]
        Restart=always
        Type=simple
        ExecStartPre=/opt/beserver/get-azure-env.sh
        ExecStart=/opt/bin/docker-compose -f /opt/beserver/docker-compose.yml up
        ExecStop=/opt/bin/docker-compose -f /opt/beserver/docker-compose.yml down
        ExecReload=/opt/bin/docker-compose -f /opt/beserver/docker-compose.yml restart

        [Install]
        WantedBy=multi-user.target
